# Generated by Django 5.2.5 on 2025-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
