# Generated by Django 5.2.5 on 2025-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(),
        ),
    ]
